version: '3.8'

services:
  nuxt-app:
    image: seein-prydia:latest
    build:
      context: .
      args:
        ENV_PROFILE: ".env.prod"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
